# Generated by Django 5.0.6 on 2024-05-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_date_remove_post_owner_post_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='months',
            field=models.CharField(verbose_name=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(verbose_name=255),
        ),
    ]
