# Generated by Django 5.0.6 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_months_alter_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='months',
            field=models.CharField(null=True, verbose_name=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(null=True, verbose_name=255),
        ),
    ]
