# Generated by Django 5.0.6 on 2024-05-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_created_at_alter_post_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_Orderd', to='posts.post'),
        ),
    ]
