# Generated by Django 5.0.6 on 2024-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_order_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wilaya',
            field=models.CharField(default='djelfa', verbose_name=255),
        ),
    ]
