# Generated by Django 5.0.6 on 2024-05-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_file_user_is_verified_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.FileField(default=2, upload_to='uploads/profile/'),
            preserve_default=False,
        ),
    ]
