# Generated by Django 5.0.6 on 2024-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/documents/'),
        ),
    ]
